version: '3.4'
services:
  test_recognition_serv:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && make test"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/recognition_serv
    
  recognition_serv:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./recognition_serv/main.py"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/recognition_serv
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3